server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://119.29.107.133:3306/springBoot?characterEncoding=UTF-8
    username: xiaolugoo
    password: xiaolugoo
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    #database:1
      host: 127.0.0.1
      port: 6379
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
