server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://119.29.107.133:3306/springBoot?characterEncoding=UTF-8
    username: xiaolugoo
    password: xiaolugoo
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect